### ISSUE TITLE
关于JarLauncher的思考

### ISSUE THREAD

**Issue by zhang852774731** [mercyblitz/thinking-in-spring-boot-samples#10]
SpringBoot为什么要重新写一套解析嵌套Jar的东西。就比如A.jar，里边引用了B.jar和C.jar，那么A.jar就是一个嵌套的jar，在运行A.jar的时候，可以把B.jar和C.jar设置到classpath中，这种方式也可以运行啊。
不知道我的理解对不对。

**Comment by mercyblitz** [comment]
因为要符合流行的虚拟化技术中的镜像
