### ISSUE TITLE
P113页，Conditional 注解拼写错误

### ISSUE THREAD

**Issue by bilaisheng** [mercyblitz/thinking-in-spring-boot-samples#13]
P113页，Conditional 注解拼写错误
正文第六行。@Configuration和@Condtianl的联系：

【Condtinal】 单词拼写少了个【i】

**Comment by mercyblitz** [comment]
感谢 @bilaisheng 的反馈，该问题已被记录，请参考 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-485350266
