### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by verichenn** [mercyblitz/thinking-in-spring-boot-samples#22]
P239 第五行 <context:annotation-config>中间多了一个空格
---
✅ 感谢 @verichenn 反馈，已确认排版错误并收录~

**Comment by verichenn** [comment]
P240 第四行Ordered.HIGHEST_PRECEDENCE 中间多了一个空格

**Comment by verichenn** [comment]
**P250** 【8.2.1小节】正文第一行 `code-based`中间多一个空格

**Comment by lianpeng0011** [comment]
P68  Spring IO Platorm 项目名称拼写错误 ，少了一个f

**Comment by verichenn** [comment]
P216  `理论上，运行结果...` 行 `txManager2`拼写有误

**Comment by verichenn** [comment]
**P251** 最后一段文档引用 第一行 `code-based` 多一个空格；第三行`...implementation of this interace...` `interace` 应该是 `interface` (官方文档笔误？)
