### ISSUE TITLE
issue-文件名过长，导致克隆失败

### ISSUE THREAD

**Issue by runbird** [mercyblitz/thinking-in-spring-boot-samples#23]
git clone到本地的时候，提示错误信息如下：
`error: unable to create file spring-boot-2.0-samples/externalized-configuration-sample/src/main/java/thinking/in/spring/boot/samples/externalized/configuration/bootstrap/ConfigurationPropertiesExternalizedConfigurationBootstrap.java (Filename too long)`

**Comment by timoCaptain** [comment]
git config --global core.longpaths true
