### ISSUE TITLE
451页和467页对SimpleApplicationEvenMulticaster说法 不一致

### ISSUE THREAD

**Issue by xminj** [mercyblitz/thinking-in-spring-boot-samples#24]
451页原文：已知SimpleApplicationEvenMulticaster既是Spring Boot事件广播实现，也是Spring事件发布的实现。
![图片](https://user-images.githubusercontent.com/34179109/58176867-d3838180-7cd5-11e9-8c31-339034c76607.png)

467页原文：已知SimpleApplicationEvenMulticaster既是Spring Boot事件广播实现，也是Spring事件广播的实现。
![图片](https://user-images.githubusercontent.com/34179109/58176925-f2821380-7cd5-11e9-9d61-6745e26f7f7a.png)

**Comment by mercyblitz** [comment]
这两处并不报名，不过第一处的说法有些不严谨：
“也是Spring事件发布的实现” 调整为 "也是Spring事件发布的底层实现” 或许更好理解
