### ISSUE TITLE
前言 XIII 表达约定

### ISSUE THREAD

**Issue by morningcat2018** [mercyblitz/thinking-in-spring-boot-samples#26]
本书的讨论内容可能对相同事务出现不同表述方式
其中“事务”是不是应该为“事物”？

**Comment by mercyblitz** [comment]
感谢 @morningcat2018 反馈，反馈该问题已收录 
请参考：https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-485239605
