### ISSUE TITLE
【勘误记录】2019年5月第三次印刷

### ISSUE THREAD

**Issue by LJaer** [mercyblitz/thinking-in-spring-boot-samples#31]
P15 mvn dependency:tree -Dincludes=org.springframework* , 其中 - 和 D 之间多了空格
---
感谢 @LJaer 的反馈 ，该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/16#issue-435711793 记录

**Comment by LJaer** [comment]
P43 倒数第8行，故符合故符合重复多次

**Comment by zssgshr** [comment]
第277页 8.3.3 配置条件装配原理
@Profile("java7")所标注的LambdaCaculatingService并未注册在spring应用上下文，应该是”标注的IterationCaculatingService”
