### ISSUE TITLE
43页第7行

### ISSUE THREAD

**Issue by a974389757** [mercyblitz/thinking-in-spring-boot-samples#32]
第七行开始的这句话“xxx.startWith(BOOT_INF_CLASS)的判断”，在上面贴的代码里并未找到这句代码，只找到了“entry.getName().equals(BOOT_INF_CLASS)”和“entry.getName().startWith(BOOT_INF_LIB)”

**Comment by mercyblitz** [comment]
感谢反馈，该错误已被记录
https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-484749074
