### ISSUE TITLE
第166页packageSearchPath的变量值书写有误

### ISSUE THREAD

**Issue by zhuangjinjin** [mercyblitz/thinking-in-spring-boot-samples#33]
第166页原文：默认情况下，处理后的packageSearchPath为”classpath*:thinking/in/spring/boot/***/.class“。

修正：”classpath*:thinking/in/spring/boot/**/*.class“

**Comment by mercyblitz** [comment]
感谢反馈，该问题已被记录 
https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-487267758
