### ISSUE TITLE
第98页，上数13行，@EnableAutoConfigura tion多了一个空格

### ISSUE THREAD

**Issue by outpaces** [mercyblitz/thinking-in-spring-boot-samples#43]
第98页，上数13行开头，@EnableAutoConfigura tion多了一个空格

**Comment by mercyblitz** [comment]
请问您书籍印刷次数是多少呢？

**Comment by Gsealy** [comment]
> 请问您书籍印刷次数是多少呢？

相同问题，19年7月第5次印刷

**Comment by qwm876677344** [comment]
第一次




------------------ 原始邮件 ------------------
发件人: "Gsealy"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 下午5:54
收件人: "mercyblitz/thinking-in-spring-boot-samples"<thinking-in-spring-boot-samples@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [mercyblitz/thinking-in-spring-boot-samples] 第98页，上数13行，@EnableAutoConfigura tion多了一个空格 (#43)



 
请问您书籍印刷次数是多少呢？
  
相同问题，19年7月第5次印刷

**Comment by mercyblitz** [comment]
感谢 @outpaces 的反馈，该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-541413176 中记录
