### ISSUE TITLE
P170页中缺少空格

### ISSUE THREAD

**Issue by dwlsxj** [mercyblitz/thinking-in-spring-boot-samples#47]
P170中第一行如下所示：
`没有标注@Component的情况下，通过sanner.addIncludeFilter(newAnnotationTypeFilter(Service.class))的方式达到识别@Service所标注类的目的`

其中`newAnnotationTypeFilter(Service.class)`的`new`没有空格隔开`new AnnotationTypeFilter(Service.class)`

**Comment by mercyblitz** [comment]
该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-500304285 中记录~
