### ISSUE TITLE
P181 最下面的源码应该不是来自3.0.0

### ISSUE THREAD

**Issue by xiaobei-ihmhny** [mercyblitz/thinking-in-spring-boot-samples#48]
RecursiveAnnotationAttributesVisitor这个类是从3.1.1才有的
![RecursiveAnnotationAttributesVisitor](https://user-images.githubusercontent.com/26052371/62002264-137e3f00-b133-11e9-9a3d-844261365dd4.png)
而书中却是按3.0.0来分析的
![0a18b1be5ae9a5f5d826421736dc8b8](https://user-images.githubusercontent.com/26052371/62002273-3dcffc80-b133-11e9-92eb-79775871dae3.jpg)

**Comment by mercyblitz** [comment]
感谢反馈，该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-487298206 中提到，在下次印刷时会修复~
