### ISSUE TITLE
548页 11.3.4 执行CommandLineRunner和ApplicationRunner

### ISSUE THREAD

**Issue by itxingfeichen** [mercyblitz/thinking-in-spring-boot-samples#54]
中部分，“spring上下文中出现多个CommandLineRunner或ApplicationRunner排序可通过实现Ordered接口或标注**@Oreer**注解”，**@Oreer应该为@Order**。

**Comment by mercyblitz** [comment]
感谢反馈，该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-501131009 中提到，等待下一次印刷修复~
