### ISSUE TITLE
第7页,配置Maven仓库，文件位置表述不够精准

### ISSUE THREAD

**Issue by nzmc663** [mercyblitz/thinking-in-spring-boot-samples#56]
maven settings.xml文件存放在$M2_HOME/conf目录下，而不是$M2_HOME/config。

**Comment by mercyblitz** [comment]
感谢反馈，该问题在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-533764666 中反馈
