### ISSUE TITLE
P431 最后一段单词间缺少空格

### ISSUE THREAD

**Issue by justmehyp** [mercyblitz/thinking-in-spring-boot-samples#62]
P431 最后一段，SimpleApplicationEventMulticasterinitialMulticaster 中间缺少空格，应为 SimpleApplicationEventMulticaster initialMulticaster。

**Comment by mercyblitz** [comment]
感谢反馈，该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-541413176 中反馈，请参考~
