### ISSUE TITLE
6月第4次印刷版本P26执行”sh mvnw spring-boot:run“以后Maven的zip文件的解压问题

### ISSUE THREAD

**Issue by McJayFeng** [mercyblitz/thinking-in-spring-boot-samples#64]
”...随后将其解压到/Users/mercyblitz/.m2/wrapper目录，即$M2_HOME/.m2/wrapper目录，....“，此处的”$M2_HOME/.m2/wrapper目录“应该是”~/.m2/wrapper目录“吧？

**Comment by mercyblitz** [comment]
感谢反馈，已确认编写错误并收录~
