### ISSUE TITLE
P153 @Import 和 @ImportResource起始版本应该都是3.0，书上写的是2.5

### ISSUE THREAD

**Issue by wanglforever** [mercyblitz/thinking-in-spring-boot-samples#65]
P153 @Import 和 @ImportResource起始版本应该都是3.0，书上写的是2.5，P226也有写@Import是Spring Framework3.0 新引入的Annotation，前后有矛盾

**Comment by mercyblitz** [comment]
感谢反馈，该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-491857986 中反馈~
