### ISSUE TITLE
2019年5月第3次印刷：390页第11、13行印刷错误

### ISSUE THREAD

**Issue by illman2016** [mercyblitz/thinking-in-spring-boot-samples#67]
##2019第一版第3次印刷：390页第11、13行印刷错误

1、
11行：URLStreamHandler扩展机制，所有**AbstractApplication** 实例和任意DefaultResourceLoader

修正：AbstractApplication 应该改为 **AbstractApplicationContext**, 是Spring Framework抽象应用上下文类，Spring体系是没有AbstractApplication这个对象的

2、
13行：当ProtocolResolver出现并能够在运行时增加到**AbstractApplication** 实例中后，两者的差异就出现了

修正：AbstractApplication 应该改为 **AbstractApplicationContext**,是Spring Framework抽象上下文类，Spring体系是没有AbstractApplication这个对象的

**Comment by mercyblitz** [comment]
✅ 谢谢 @illman2016 的反馈，该问题已被收录，属于“编写”错误
