### ISSUE TITLE
项目依赖无法resolved

### ISSUE THREAD

**Issue by buffinside** [mercyblitz/thinking-in-spring-boot-samples#68]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
**[INFO] Building 《Spring Boot 编程思想》传统 Servlet 示例工程 1.0.0-SNAPSHOT**
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for thinking-in-spring-boot:shared-servlet31:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.386 s
[INFO] Finished at: 2019-11-22T14:57:31+08:00
[INFO] Final Memory: 7M/40M
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal on project servlet-sample: Could not resolve dependencies for project thinking-in-spring-boot:servlet-sample:war:1.0.0-SNAPSHOT: Could not find artifact thinking-in-spring-boot:shared-servlet31:jar:1.0.0-SNAPSHOT -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1

**Comment by mercyblitz** [comment]
请使用 Maven 3.6 + 以上的版本，经过本地多次尝试，没有发现问题~
