### ISSUE TITLE
153页@Primary 和 @Role 注解的场景描述都应该为：替换XML属性。。。

### ISSUE THREAD

**Issue by 1993heqiang** [mercyblitz/thinking-in-spring-boot-samples#69]
`@Primary`注释：
This annotation is semantically equivalent to the element's primary attribute in Spring XML.

**Comment by 1993heqiang** [comment]
@Primary注释：
This annotation is semantically equivalent to the <bean> element's primary **attribute** in Spring XML.

**Comment by mercyblitz** [comment]
感谢反馈，经过对比，并没有发现明显的瑕疵~
