### ISSUE TITLE
第61页，spring-boot-starter-parent 的pom 有误

### ISSUE THREAD

**Issue by clancytom** [mercyblitz/thinking-in-spring-boot-samples#76]
小马哥，终于买到实体书了，artifactId 貌似有问题，应该是spring-boot-starter-parent 而不应该是spring-boot-parent吧。
还有69页，倒数第二行，就能引到Tomcat容器，而不应该是就能引导Tomcat容器吧

**Comment by mercyblitz** [comment]
artifactId 是没有问题的，请参考 ：https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-parent/pom.xml

是引导，而非引到，引导就是启动的意思
