### ISSUE TITLE
P181页 代码版本问题

### ISSUE THREAD

**Issue by cxp4** [mercyblitz/thinking-in-spring-boot-samples#78]
3.0.0.RELEASE里 `AnnotationAttributesReadingVisitor` 并没有继承 `RecursiveAnnotationAttributesVisitor` 且没有doVisitEnd 方法。
3.1.4里开始有继承，并且有方法`doVisitEnd` 等方法

**Comment by cxp4** [comment]
P181页 代码版本问题

**Comment by mercyblitz** [comment]
感谢 @cxp4 反馈，该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-487298206 反馈，并在新印刷中修正。
