### ISSUE TITLE
P480 代码对应错误

### ISSUE THREAD

**Issue by Ghost-LD** [mercyblitz/thinking-in-spring-boot-samples#81]
构建泛型事件代码错误
应为：public static class GenericEvent<泛型> 
            extends ApplicationEvent implements ResolvableTypeProvider

**Comment by mercyblitz** [comment]
感谢 @Ghost-LD 反馈，该问题已在 https://github.com/mercyblitz/thinking-in-spring-boot-samples/issues/3#issuecomment-499355118 反馈
