### ISSUE TITLE
63页依赖maven-war-plugin的版本为2.2没有说清楚为什么。

### ISSUE THREAD

**Issue by cechaodeng** [mercyblitz/thinking-in-spring-boot-samples#82]
本方式仅关注<dependencyManagement>，所以maven-war-plugin采用的版本为2.2，这句不理解是为什么。

**Comment by mitays** [comment]
这里的意思应该是<dependencyManagement>方式导入spring-boot-dependencies，就只会引入spring-boot-dependencies中的<dependencyManagement>标签下的内容，而maven-war-plugin在其<build>标签下，故而不起作用；使用默认的2.2版本打包

**Comment by mercyblitz** [comment]
感谢老铁回复~
