### ISSUE TITLE
【勘误】单词拼写错误

### ISSUE THREAD

**Issue by xkcoding** [mercyblitz/thinking-in-spring-boot-samples#9]
103 页正文第二段。

> 尽管 @CompoentScan 仅关注于 @Component，然而由于 ......

~~`@CompoentScan`~~ 修改为 `@ComponentScan`，望小马哥确认该问题！

PS：正文第二段中所有出现 ~~`@CompoentScan`~~ 均拼写错误，需要修改为 `@ComponentScan`

**Comment by mercyblitz** [comment]
@xkcoding 

✅ 谢谢反馈，已确认拼写错误并收录~
